databases:
  - name: OK Ryusei_DB
    databaseName: ok_ryusei_db
    user: Muscle_Routing
    region: singapore

services:
  - type: web
    name: Muscle Routing
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Muscle_Routing
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

